module.exports = {
  FETCH_ALL_CASES_REQUEST: "FETCH_ALL_COUNTRY_REQUEST",
  FETCH_ALL_CASES_SUCCESS: "FETCH_ALL_COUNTRY_SUCCESS",
  FETCH_ALL_CASES_FAILURE: "FETCH_ALL_COUNTRY_FAILURE",
  FETCH_COUNTRY_CASES_REQUEST: "FETCH_COUNTRY_CASES_REQUEST",
  FETCH_COUNTRY_CASES_SUCCESS: "FETCH_COUNTRY_CASES_SUCCESS",
  FETCH_COUNTRY_CASES_FAILURE: "FETCH_COUNTRY_CASES_FAILURE",
  FETCH_GRAPH_CASES_REQUEST: "FETCH_GRAPH_CASES_REQUEST",
  FETCH_GRAPH_CASES_SUCCESS: "FETCH_GRAPH_CASES_SUCCESS",
  FETCH_GRAPH_CASES_FAILURE: "FETCH_GRAPH_CASES_FAILURE",
};
